version: '3.3'
services:
        drupal:
                image: drupal:latest
                ports:
                        - 80:80
                volumes:
                        - /var/www/html/modules
                        - /var/www/html/profiles
                        - /var/www/html/themes
                restart: always

        mysql:
                image: mysql:latest
                environment:
                        - MYSQL_DATABASE=drupal
                        - MYSQL_USER=user
                        - MYSQL_PASSWORD=password
                        - MYSQL_ROOT_PASSWORD=password
                restart: always
